--
-- PostgreSQL database dump
--

-- Dumped from database version 13.6
-- Dumped by pg_dump version 13.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: actors; Type: TABLE; Schema: public; Owner: mahumhaider
--

CREATE TABLE public.actors (
    id integer NOT NULL,
    name character varying NOT NULL,
    age integer NOT NULL,
    gender character varying NOT NULL
);


ALTER TABLE public.actors OWNER TO mahumhaider;

--
-- Name: actors_id_seq; Type: SEQUENCE; Schema: public; Owner: mahumhaider
--

CREATE SEQUENCE public.actors_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.actors_id_seq OWNER TO mahumhaider;

--
-- Name: actors_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: mahumhaider
--

ALTER SEQUENCE public.actors_id_seq OWNED BY public.actors.id;


--
-- Name: movies; Type: TABLE; Schema: public; Owner: mahumhaider
--

CREATE TABLE public.movies (
    id integer NOT NULL,
    title character varying NOT NULL,
    release_date character varying NOT NULL
);


ALTER TABLE public.movies OWNER TO mahumhaider;

--
-- Name: movies_id_seq; Type: SEQUENCE; Schema: public; Owner: mahumhaider
--

CREATE SEQUENCE public.movies_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.movies_id_seq OWNER TO mahumhaider;

--
-- Name: movies_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: mahumhaider
--

ALTER SEQUENCE public.movies_id_seq OWNED BY public.movies.id;


--
-- Name: actors id; Type: DEFAULT; Schema: public; Owner: mahumhaider
--

ALTER TABLE ONLY public.actors ALTER COLUMN id SET DEFAULT nextval('public.actors_id_seq'::regclass);


--
-- Name: movies id; Type: DEFAULT; Schema: public; Owner: mahumhaider
--

ALTER TABLE ONLY public.movies ALTER COLUMN id SET DEFAULT nextval('public.movies_id_seq'::regclass);


--
-- Data for Name: actors; Type: TABLE DATA; Schema: public; Owner: mahumhaider
--

COPY public.actors (id, name, age, gender) FROM stdin;
1	Mjjj	29	female
2	Scarlt Johanson	39	female
3	Luca Brody	49	male
4	Jack Davon	56	male
5	Justin Biber	27	male
\.


--
-- Data for Name: movies; Type: TABLE DATA; Schema: public; Owner: mahumhaider
--

COPY public.movies (id, title, release_date) FROM stdin;
3	The batman	2018
1	Godfather	2018
2	Dangle	1987
4	The irishman	2004
5	Troy	1974
\.


--
-- Name: actors_id_seq; Type: SEQUENCE SET; Schema: public; Owner: mahumhaider
--

SELECT pg_catalog.setval('public.actors_id_seq', 45, true);


--
-- Name: movies_id_seq; Type: SEQUENCE SET; Schema: public; Owner: mahumhaider
--

SELECT pg_catalog.setval('public.movies_id_seq', 15, true);


--
-- Name: actors actors_pkey; Type: CONSTRAINT; Schema: public; Owner: mahumhaider
--

ALTER TABLE ONLY public.actors
    ADD CONSTRAINT actors_pkey PRIMARY KEY (id);


--
-- Name: movies movies_pkey; Type: CONSTRAINT; Schema: public; Owner: mahumhaider
--

ALTER TABLE ONLY public.movies
    ADD CONSTRAINT movies_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

